import Responsibility from "./madules/Responsibility.js";
import Down from "./madules/down.js";
import Footer from "./madules/footer.js";
import Introduce from "./madules/introduce.js";
import Menu from "./madules/menu.js";
import Nut from "./madules/nut.js";
import Nutarticle from "./madules/nutarticle.js";
import Nutbox from "./madules/nutbox.js";
import Pastel from "./madules/pastel.js";
import Posts from "./madules/posts.js";
import Recepe from "./madules/recepe.js";
import Rice from "./madules/rice.js";
import Ricebox from "./madules/ricebox.js";
import Rokn1 from "./madules/rokn1.js";
import Side from "./madules/side.js";
import TEA from "./madules/tea.js";
import Teaarticle from "./madules/teaarticle.js";
import Teabox from "./madules/teabox.js";
import Videos from "./madules/video.js";

Menu();
Side();
Introduce();
Pastel();
Rice();
Ricebox();
Rokn1();
TEA();
Teabox();
Teaarticle();
Nut();
Nutarticle();
Nutbox();
Posts();
Videos();
Responsibility();
Footer();
Down();
Recepe();
